twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        main_menu:
            - { label: 'label.menu', route: '' }
            - { label: 'label.menu', route: '' }
            - { label: 'label.menu', route: '' }